runtime: java17
env: standard
instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

env_variables:
  SPRING_PROFILES_ACTIVE: "gcp"
  SPRING_DATASOURCE_URL: "jdbc:mysql:///zm_data_base?cloudSqlInstance=zm-auto-rental-app-company:us-central1:zm-mysql-instance&socketFactory=com.google.cloud.sql.mysql.SocketFactory&user=root"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "YOUR_DB_PASSWORD"  # You'll need to set this in the console

service: default 