steps:
  # Build the application
  - name: 'maven:3.8.4-openjdk-17'
    entrypoint: mvn
    args: ['package', '-DskipTests']

  # Deploy to App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'app'
      - 'deploy'
      - 'app.yaml'
      - '--project=zm-auto-rental-app-company'
      - '--quiet' 