ALTER TABLE user
ADD COLUMN Email_verified BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN Phone_verified BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN Auth_token VARCHAR(255),
ADD COLUMN Token_expiry TIMESTAMP;